### ISSUE TITLE
boundary_role is created with invalid grants and cannot be updated without deleting it

### ISSUE THREAD

**Issue by Alan-pad** [hashicorp/terraform-provider-boundary#172]
Hi there,

I'd like to report a bug on `boundary_role` resource.

### Terraform Version

```
Terraform v1.0.11
on linux_amd64
```

### Affected Resource(s)

- boundary_role

### Terraform Configuration Files
```hcl
resource "boundary_role" "project_scope" {
  for_each = {
    for value in local.roles : "${value.auth_method}-${value.name}" => value
    if value.catalog == null && value.host_set == null
  }
  name          = each.key
  description   = "Access to target in ${each.value.project}/*"
  principal_ids = [boundary_managed_group.this["${each.value.auth_method}-${each.value.name}"].id]
  grant_strings = ["type=target;actions=authorize-session"]
  scope_id      = boundary_scope.projects[each.value.project].id
}
```

### Debug Output

https://gist.github.com/Alan-pad/0354b402f7569b30eb0daba561ac717e

### Expected Behavior

Creating a role with invalid grant and then updating it with another grant should result in a resource update in terraform.

### Actual Behavior

Creating a role with invalid grant and then updating it with another grant results in resource creation failure because resource already exists.

Here's the error we're getting while reapplying :

```
{"kind":"InvalidArgument","message":"Invalid request.  Request attempted to make second resource with the same field value that must be unique."}
```

### Steps to Reproduce

1. Create boundary_role with an invalid grant using terraform apply
2. Modify boundary_role with another grant and launch terraform apply 

### Important Factoids

- Boundary Controller deployed on **Kubernetes**
- Boundary version : **0.7.3**
- Local TF State

### References

I did not find any reference to this.

**Comment by Alan-pad** [comment]
Oh I saw a commit that should fix this issue I'd imagine : https://github.com/hashicorp/terraform-provider-boundary/commit/cbcbdc9955356e4a36ed8c74d031f2e9520e2855.
If that's the case I'll close it ;)

**Comment by malnick** [comment]
Thanks @Alan-pad - can you verify that this was fixed?

**Comment by Alan-pad** [comment]
I don't think it's fixed yet since there was no new release and I wasn't able to test the master version I'm having a bit of trouble setting it up as a dev version

**Comment by PPacent** [comment]
Thanks @Alan-pad, we will close this issue as the Boundary Terraform provider has now had multiple new releases that includes this commit. Thank you for raising this!
